
def write_globals():
  s=(
    "class address\n"
    "{\n"
    "  public static String addr_init=\"0\";\n"
    "  public String id;\n"
    "  public int balance;\n"
    "  public address() { id=addr_init+\"1\"; }\n"
    "  public address(String id_)\n"
    "  {\n"
    "    id=id_;\n"
    "  }\n"
    "  public void fallback() {}\n"
    "}\n"
    "\n"
    "class Message\n"
    "{\n"
    "  public address sender=new address(); // sender of the message\n"
    "  public address receiver=new address(); // recepient of the message\n" 
    "  public int value; // amount of wei to transfer\n"
    "  public int GasLimit; // \n"
    "  public String data;\n"
    "}\n"
    "\n"
    "class Globals\n"
    "{\n" 
    "  public static Message msg=new Message();\n"
    "  // max number of addresses; max depth of a transaction\n"
    "  public static int noa=10, dot=10;\n"
    "  public static int[][] trans_gaslimit=new int[noa][dot];\n"
    "  // count active depth of each transaction for each address\n"
    "  public static int[] trans_depth=new int[noa];\n"
    "  public static address[] addresses=new address[noa];\n"
    "  // address -> index\n"
    "  public static int Index(address a)\n"
    "  {\n"
    "    for(int i=0; i<noa; i++)\n"
    "      if(addresses[i]==a)\n"
    "        return i;\n"
    "    return -1;\n"
    "  }\n"
    "  public static boolean send (\n"
    "    address from,\n"
    "    address to,\n"
    "    address old_sender,\n"
    "    address old_receiver,\n"
    "    int value,\n"
    "    int GasLimit,\n"
    "    String data)\n"
    "  {\n"
    "     if(from.balance<value)\n"
    "     {\n"
    "       return false;\n"
    "     }\n"
    "  //   // MSG-a\n"
    "    msg.sender=from;\n"
    "    msg.receiver=to;\n"
    "    msg.value=value;\n"
    "    to.balance += value;\n"
    "    from.balance -= value;\n"
    "    int id=Index(to);\n"
    "    trans_depth[id]++;\n"
    "    trans_gaslimit[id][trans_depth[id]]=0;\n"
    "    \n"
    "    to.fallback();\n"
    "    msg.sender=old_sender;\n"
    "    msg.receiver=old_receiver;\n"
    "    trans_depth[id]--;\n"
    "    if(trans_gaslimit[id][trans_depth[id]]>GasLimit)\n"
    "    { \n"
    "      return false;\n"
    "    }\n"
    "    else\n"
    "    {\n"
    "       return true;\n"
    "    }\n"
    "  }\n"
    "}\n"
    "\n"
  )
  
  return s

def write_main():
  s=""
  s+="public class Veri\n"
  s+="{\n"
  s+="  public "
  s+="static void main(String [] args)\n"
  s+="  {\n"
  s+="    Env.init();\n"
  s+="  }\n"
  s+="}\n"
  return s
